export { HeroSection } from "./hero"
export { LogoCloudSection } from "./logo-cloud"
export { StatsBarSection } from "./stats-bar"
export { DeliverablesSection } from "./deliverables"
export { ProofSection } from "./proof"
export { ComparisonSection } from "./comparison"
export { PricingSection } from "./pricing"
export { CTASection } from "./cta"
